### ISSUE TITLE
更新完 他回复的信息变了

### ISSUE THREAD

**Issue by ajchen02** [mas-alone/nonebot-plugin-sayoroll#2]
![image](https://github.com/mas-alone/nonebot-plugin-sayoroll/assets/88434425/e7615ceb-0661-464a-a9b4-232b9bc3ec95)
我还是喜欢之前的“你的数字是...”...

**Comment by mas-alone** [comment]
79行
`msg = '{}'.format(random.randint(1, 100))`
改为
`msg = '你的数字是 {}'.format(random.randint(1, 100))`

同理 85行
`msg = '你的数字是 {}'.format(random.randint(1, num))`
